### PR TITLE
Render data if first page is less than maximum page size

### LINKED ISSUE #1: No data return
No data return at table lever.
I have less than 100 records, maybe that is the issue here...

### PR DESCRIPTION
**Pull request by jesseczko**
Likely fixes: https://github.com/areknawo/Using-AG-Grid-React-UI-with-Remix.run/issues/1

https://www.ag-grid.com/javascript-data-grid/infinite-scrolling/#setting-last-row-index

### CODE REVIEW

**Comment by areknawo** [comment]
Hi, Thanks for the PR. Will verify it and the related issue, but from a quick look it seems like some code is missing.
Could you take a look at that? Thanks!

**Comment by JesseChezenko-AI** [comment]
Hi sorry I missed that. Thanks for fixing it up!

**Comment by jesseczko** [comment]
Sorry I missed that. Thanks for fixing it up and integrating!

**Comment by areknawo** [comment]
No problem! Thanks for the idea and sorry it took me so long to merge.

**Pull request merged**
